<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo;

/**
 * Protobuf message : pokemongo.RequestEnvelop
 */
class RequestEnvelop extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * unknown1 required int32 = 1
     *
     * @var int
     */
    protected $unknown1 = null;

    /**
     * rpc_id optional int64 = 3
     *
     * @var int
     */
    protected $rpc_id = null;

    /**
     * requests repeated message = 4
     *
     * @var \Protobuf\Collection<\Protobuf\PokemonGo\RequestEnvelop\Requests>
     */
    protected $requests = null;

    /**
     * unknown6 optional message = 6
     *
     * @var \Protobuf\PokemonGo\RequestEnvelop\Unknown6
     */
    protected $unknown6 = null;

    /**
     * latitude optional fixed64 = 7
     *
     * @var int
     */
    protected $latitude = null;

    /**
     * longitude optional fixed64 = 8
     *
     * @var int
     */
    protected $longitude = null;

    /**
     * altitude optional fixed64 = 9
     *
     * @var int
     */
    protected $altitude = null;

    /**
     * auth optional message = 10
     *
     * @var \Protobuf\PokemonGo\RequestEnvelop\AuthInfo
     */
    protected $auth = null;

    /**
     * unknown11 optional message = 11
     *
     * @var \Protobuf\PokemonGo\UnknownAuth
     */
    protected $unknown11 = null;

    /**
     * unknown12 optional int64 = 12
     *
     * @var int
     */
    protected $unknown12 = null;

    /**
     * Check if 'unknown1' has a value
     *
     * @return bool
     */
    public function hasUnknown1()
    {
        return $this->unknown1 !== null;
    }

    /**
     * Get 'unknown1' value
     *
     * @return int
     */
    public function getUnknown1()
    {
        return $this->unknown1;
    }

    /**
     * Set 'unknown1' value
     *
     * @param int $value
     */
    public function setUnknown1($value)
    {
        $this->unknown1 = $value;
    }

    /**
     * Check if 'rpc_id' has a value
     *
     * @return bool
     */
    public function hasRpcId()
    {
        return $this->rpc_id !== null;
    }

    /**
     * Get 'rpc_id' value
     *
     * @return int
     */
    public function getRpcId()
    {
        return $this->rpc_id;
    }

    /**
     * Set 'rpc_id' value
     *
     * @param int $value
     */
    public function setRpcId($value = null)
    {
        $this->rpc_id = $value;
    }

    /**
     * Check if 'requests' has a value
     *
     * @return bool
     */
    public function hasRequestsList()
    {
        return $this->requests !== null;
    }

    /**
     * Get 'requests' value
     *
     * @return \Protobuf\Collection<\Protobuf\PokemonGo\RequestEnvelop\Requests>
     */
    public function getRequestsList()
    {
        return $this->requests;
    }

    /**
     * Set 'requests' value
     *
     * @param \Protobuf\Collection<\Protobuf\PokemonGo\RequestEnvelop\Requests> $value
     */
    public function setRequestsList(\Protobuf\Collection $value = null)
    {
        $this->requests = $value;
    }

    /**
     * Add a new element to 'requests'
     *
     * @param \Protobuf\PokemonGo\RequestEnvelop\Requests $value
     */
    public function addRequests(\Protobuf\PokemonGo\RequestEnvelop\Requests $value)
    {
        if ($this->requests === null) {
            $this->requests = new \Protobuf\MessageCollection();
        }

        $this->requests->add($value);
    }

    /**
     * Check if 'unknown6' has a value
     *
     * @return bool
     */
    public function hasUnknown6()
    {
        return $this->unknown6 !== null;
    }

    /**
     * Get 'unknown6' value
     *
     * @return \Protobuf\PokemonGo\RequestEnvelop\Unknown6
     */
    public function getUnknown6()
    {
        return $this->unknown6;
    }

    /**
     * Set 'unknown6' value
     *
     * @param \Protobuf\PokemonGo\RequestEnvelop\Unknown6 $value
     */
    public function setUnknown6(\Protobuf\PokemonGo\RequestEnvelop\Unknown6 $value = null)
    {
        $this->unknown6 = $value;
    }

    /**
     * Check if 'latitude' has a value
     *
     * @return bool
     */
    public function hasLatitude()
    {
        return $this->latitude !== null;
    }

    /**
     * Get 'latitude' value
     *
     * @return int
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Set 'latitude' value
     *
     * @param int $value
     */
    public function setLatitude($value = null)
    {
        $this->latitude = $value;
    }

    /**
     * Check if 'longitude' has a value
     *
     * @return bool
     */
    public function hasLongitude()
    {
        return $this->longitude !== null;
    }

    /**
     * Get 'longitude' value
     *
     * @return int
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Set 'longitude' value
     *
     * @param int $value
     */
    public function setLongitude($value = null)
    {
        $this->longitude = $value;
    }

    /**
     * Check if 'altitude' has a value
     *
     * @return bool
     */
    public function hasAltitude()
    {
        return $this->altitude !== null;
    }

    /**
     * Get 'altitude' value
     *
     * @return int
     */
    public function getAltitude()
    {
        return $this->altitude;
    }

    /**
     * Set 'altitude' value
     *
     * @param int $value
     */
    public function setAltitude($value = null)
    {
        $this->altitude = $value;
    }

    /**
     * Check if 'auth' has a value
     *
     * @return bool
     */
    public function hasAuth()
    {
        return $this->auth !== null;
    }

    /**
     * Get 'auth' value
     *
     * @return \Protobuf\PokemonGo\RequestEnvelop\AuthInfo
     */
    public function getAuth()
    {
        return $this->auth;
    }

    /**
     * Set 'auth' value
     *
     * @param \Protobuf\PokemonGo\RequestEnvelop\AuthInfo $value
     */
    public function setAuth(\Protobuf\PokemonGo\RequestEnvelop\AuthInfo $value = null)
    {
        $this->auth = $value;
    }

    /**
     * Check if 'unknown11' has a value
     *
     * @return bool
     */
    public function hasUnknown11()
    {
        return $this->unknown11 !== null;
    }

    /**
     * Get 'unknown11' value
     *
     * @return \Protobuf\PokemonGo\UnknownAuth
     */
    public function getUnknown11()
    {
        return $this->unknown11;
    }

    /**
     * Set 'unknown11' value
     *
     * @param \Protobuf\PokemonGo\UnknownAuth $value
     */
    public function setUnknown11(\Protobuf\PokemonGo\UnknownAuth $value = null)
    {
        $this->unknown11 = $value;
    }

    /**
     * Check if 'unknown12' has a value
     *
     * @return bool
     */
    public function hasUnknown12()
    {
        return $this->unknown12 !== null;
    }

    /**
     * Get 'unknown12' value
     *
     * @return int
     */
    public function getUnknown12()
    {
        return $this->unknown12;
    }

    /**
     * Set 'unknown12' value
     *
     * @param int $value
     */
    public function setUnknown12($value = null)
    {
        $this->unknown12 = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['unknown1'])) {
            throw new \InvalidArgumentException('Field "unknown1" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'rpc_id' => null,
            'requests' => [],
            'unknown6' => null,
            'latitude' => null,
            'longitude' => null,
            'altitude' => null,
            'auth' => null,
            'unknown11' => null,
            'unknown12' => null
        ], $values);

        $message->setUnknown1($values['unknown1']);
        $message->setRpcId($values['rpc_id']);
        $message->setUnknown6($values['unknown6']);
        $message->setLatitude($values['latitude']);
        $message->setLongitude($values['longitude']);
        $message->setAltitude($values['altitude']);
        $message->setAuth($values['auth']);
        $message->setUnknown11($values['unknown11']);
        $message->setUnknown12($values['unknown12']);

        foreach ($values['requests'] as $item) {
            $message->addRequests($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'RequestEnvelop',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'unknown1',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'rpc_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'requests',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.pokemongo.RequestEnvelop.Requests'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'unknown6',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pokemongo.RequestEnvelop.Unknown6'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 7,
                    'name' => 'latitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 8,
                    'name' => 'longitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 9,
                    'name' => 'altitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 10,
                    'name' => 'auth',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pokemongo.RequestEnvelop.AuthInfo'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 11,
                    'name' => 'unknown11',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pokemongo.UnknownAuth'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 12,
                    'name' => 'unknown12',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->unknown1 === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop#unknown1" (tag 1) is required but has no value.');
        }

        if ($this->unknown1 !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->unknown1);
        }

        if ($this->rpc_id !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->rpc_id);
        }

        if ($this->requests !== null) {
            foreach ($this->requests as $val) {
                $writer->writeVarint($stream, 34);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->unknown6 !== null) {
            $writer->writeVarint($stream, 50);
            $writer->writeVarint($stream, $this->unknown6->serializedSize($sizeContext));
            $this->unknown6->writeTo($context);
        }

        if ($this->latitude !== null) {
            $writer->writeVarint($stream, 57);
            $writer->writeFixed64($stream, $this->latitude);
        }

        if ($this->longitude !== null) {
            $writer->writeVarint($stream, 65);
            $writer->writeFixed64($stream, $this->longitude);
        }

        if ($this->altitude !== null) {
            $writer->writeVarint($stream, 73);
            $writer->writeFixed64($stream, $this->altitude);
        }

        if ($this->auth !== null) {
            $writer->writeVarint($stream, 82);
            $writer->writeVarint($stream, $this->auth->serializedSize($sizeContext));
            $this->auth->writeTo($context);
        }

        if ($this->unknown11 !== null) {
            $writer->writeVarint($stream, 90);
            $writer->writeVarint($stream, $this->unknown11->serializedSize($sizeContext));
            $this->unknown11->writeTo($context);
        }

        if ($this->unknown12 !== null) {
            $writer->writeVarint($stream, 96);
            $writer->writeVarint($stream, $this->unknown12);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->unknown1 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 3);

                $this->rpc_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\RequestEnvelop\Requests();

                if ($this->requests === null) {
                    $this->requests = new \Protobuf\MessageCollection();
                }

                $this->requests->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\RequestEnvelop\Unknown6();

                $this->unknown6 = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 7) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->latitude = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 8) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->longitude = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 9) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->altitude = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 10) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\RequestEnvelop\AuthInfo();

                $this->auth = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 11) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\UnknownAuth();

                $this->unknown11 = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 12) {
                \Protobuf\WireFormat::assertWireType($wire, 3);

                $this->unknown12 = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->unknown1 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown1);
        }

        if ($this->rpc_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->rpc_id);
        }

        if ($this->requests !== null) {
            foreach ($this->requests as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->unknown6 !== null) {
            $innerSize = $this->unknown6->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->latitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->longitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->altitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->auth !== null) {
            $innerSize = $this->auth->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->unknown11 !== null) {
            $innerSize = $this->unknown11->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->unknown12 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown12);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->unknown1 = null;
        $this->rpc_id = null;
        $this->requests = null;
        $this->unknown6 = null;
        $this->latitude = null;
        $this->longitude = null;
        $this->altitude = null;
        $this->auth = null;
        $this->unknown11 = null;
        $this->unknown12 = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\RequestEnvelop) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->unknown1 = ($message->unknown1 !== null) ? $message->unknown1 : $this->unknown1;
        $this->rpc_id = ($message->rpc_id !== null) ? $message->rpc_id : $this->rpc_id;
        $this->requests = ($message->requests !== null) ? $message->requests : $this->requests;
        $this->unknown6 = ($message->unknown6 !== null) ? $message->unknown6 : $this->unknown6;
        $this->latitude = ($message->latitude !== null) ? $message->latitude : $this->latitude;
        $this->longitude = ($message->longitude !== null) ? $message->longitude : $this->longitude;
        $this->altitude = ($message->altitude !== null) ? $message->altitude : $this->altitude;
        $this->auth = ($message->auth !== null) ? $message->auth : $this->auth;
        $this->unknown11 = ($message->unknown11 !== null) ? $message->unknown11 : $this->unknown11;
        $this->unknown12 = ($message->unknown12 !== null) ? $message->unknown12 : $this->unknown12;
    }


}

