<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo;

/**
 * Protobuf message : pokemongo.ResponseEnvelop
 */
class ResponseEnvelop extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * unknown1 required int32 = 1
     *
     * @var int
     */
    protected $unknown1 = null;

    /**
     * unknown2 optional int64 = 2
     *
     * @var int
     */
    protected $unknown2 = null;

    /**
     * api_url optional string = 3
     *
     * @var string
     */
    protected $api_url = null;

    /**
     * unknown6 optional message = 6
     *
     * @var \Protobuf\PokemonGo\ResponseEnvelop\Unknown6
     */
    protected $unknown6 = null;

    /**
     * unknown7 optional message = 7
     *
     * @var \Protobuf\PokemonGo\UnknownAuth
     */
    protected $unknown7 = null;

    /**
     * payload repeated bytes = 100
     *
     * @var \Protobuf\Collection
     */
    protected $payload = null;

    /**
     * Check if 'unknown1' has a value
     *
     * @return bool
     */
    public function hasUnknown1()
    {
        return $this->unknown1 !== null;
    }

    /**
     * Get 'unknown1' value
     *
     * @return int
     */
    public function getUnknown1()
    {
        return $this->unknown1;
    }

    /**
     * Set 'unknown1' value
     *
     * @param int $value
     */
    public function setUnknown1($value)
    {
        $this->unknown1 = $value;
    }

    /**
     * Check if 'unknown2' has a value
     *
     * @return bool
     */
    public function hasUnknown2()
    {
        return $this->unknown2 !== null;
    }

    /**
     * Get 'unknown2' value
     *
     * @return int
     */
    public function getUnknown2()
    {
        return $this->unknown2;
    }

    /**
     * Set 'unknown2' value
     *
     * @param int $value
     */
    public function setUnknown2($value = null)
    {
        $this->unknown2 = $value;
    }

    /**
     * Check if 'api_url' has a value
     *
     * @return bool
     */
    public function hasApiUrl()
    {
        return $this->api_url !== null;
    }

    /**
     * Get 'api_url' value
     *
     * @return string
     */
    public function getApiUrl()
    {
        return $this->api_url;
    }

    /**
     * Set 'api_url' value
     *
     * @param string $value
     */
    public function setApiUrl($value = null)
    {
        $this->api_url = $value;
    }

    /**
     * Check if 'unknown6' has a value
     *
     * @return bool
     */
    public function hasUnknown6()
    {
        return $this->unknown6 !== null;
    }

    /**
     * Get 'unknown6' value
     *
     * @return \Protobuf\PokemonGo\ResponseEnvelop\Unknown6
     */
    public function getUnknown6()
    {
        return $this->unknown6;
    }

    /**
     * Set 'unknown6' value
     *
     * @param \Protobuf\PokemonGo\ResponseEnvelop\Unknown6 $value
     */
    public function setUnknown6(\Protobuf\PokemonGo\ResponseEnvelop\Unknown6 $value = null)
    {
        $this->unknown6 = $value;
    }

    /**
     * Check if 'unknown7' has a value
     *
     * @return bool
     */
    public function hasUnknown7()
    {
        return $this->unknown7 !== null;
    }

    /**
     * Get 'unknown7' value
     *
     * @return \Protobuf\PokemonGo\UnknownAuth
     */
    public function getUnknown7()
    {
        return $this->unknown7;
    }

    /**
     * Set 'unknown7' value
     *
     * @param \Protobuf\PokemonGo\UnknownAuth $value
     */
    public function setUnknown7(\Protobuf\PokemonGo\UnknownAuth $value = null)
    {
        $this->unknown7 = $value;
    }

    /**
     * Check if 'payload' has a value
     *
     * @return bool
     */
    public function hasPayloadList()
    {
        return $this->payload !== null;
    }

    /**
     * Get 'payload' value
     *
     * @return \Protobuf\Collection
     */
    public function getPayloadList()
    {
        return $this->payload;
    }

    /**
     * Set 'payload' value
     *
     * @param \Protobuf\Collection $value
     */
    public function setPayloadList(\Protobuf\Collection $value = null)
    {
        $this->payload = $value;
    }

    /**
     * Add a new element to 'payload'
     *
     * @param \Protobuf\Stream $value
     */
    public function addPayload($value)
    {
        if ($this->payload === null) {
            $this->payload = new \Protobuf\StreamCollection();
        }

        $this->payload->add(\Protobuf\Stream::wrap($value));
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['unknown1'])) {
            throw new \InvalidArgumentException('Field "unknown1" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'unknown2' => null,
            'api_url' => null,
            'unknown6' => null,
            'unknown7' => null,
            'payload' => []
        ], $values);

        $message->setUnknown1($values['unknown1']);
        $message->setUnknown2($values['unknown2']);
        $message->setApiUrl($values['api_url']);
        $message->setUnknown6($values['unknown6']);
        $message->setUnknown7($values['unknown7']);

        foreach ($values['payload'] as $item) {
            $message->addPayload($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'ResponseEnvelop',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'unknown1',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'unknown2',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'api_url',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'unknown6',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pokemongo.ResponseEnvelop.Unknown6'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 7,
                    'name' => 'unknown7',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pokemongo.UnknownAuth'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 100,
                    'name' => 'payload',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->unknown1 === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\ResponseEnvelop#unknown1" (tag 1) is required but has no value.');
        }

        if ($this->unknown1 !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->unknown1);
        }

        if ($this->unknown2 !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->unknown2);
        }

        if ($this->api_url !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->api_url);
        }

        if ($this->unknown6 !== null) {
            $writer->writeVarint($stream, 50);
            $writer->writeVarint($stream, $this->unknown6->serializedSize($sizeContext));
            $this->unknown6->writeTo($context);
        }

        if ($this->unknown7 !== null) {
            $writer->writeVarint($stream, 58);
            $writer->writeVarint($stream, $this->unknown7->serializedSize($sizeContext));
            $this->unknown7->writeTo($context);
        }

        if ($this->payload !== null) {
            foreach ($this->payload as $val) {
                $writer->writeVarint($stream, 802);
                $writer->writeByteStream($stream, $val);
            }
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->unknown1 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 3);

                $this->unknown2 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->api_url = $reader->readString($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\ResponseEnvelop\Unknown6();

                $this->unknown6 = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 7) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\UnknownAuth();

                $this->unknown7 = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 100) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                if ($this->payload === null) {
                    $this->payload = new \Protobuf\StreamCollection();
                }

                $this->payload->add($reader->readByteStream($stream));

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->unknown1 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown1);
        }

        if ($this->unknown2 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown2);
        }

        if ($this->api_url !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->api_url);
        }

        if ($this->unknown6 !== null) {
            $innerSize = $this->unknown6->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->unknown7 !== null) {
            $innerSize = $this->unknown7->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->payload !== null) {
            foreach ($this->payload as $val) {
                $size += 2;
                $size += $calculator->computeByteStreamSize($val);
            }
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->unknown1 = null;
        $this->unknown2 = null;
        $this->api_url = null;
        $this->unknown6 = null;
        $this->unknown7 = null;
        $this->payload = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\ResponseEnvelop) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->unknown1 = ($message->unknown1 !== null) ? $message->unknown1 : $this->unknown1;
        $this->unknown2 = ($message->unknown2 !== null) ? $message->unknown2 : $this->unknown2;
        $this->api_url = ($message->api_url !== null) ? $message->api_url : $this->api_url;
        $this->unknown6 = ($message->unknown6 !== null) ? $message->unknown6 : $this->unknown6;
        $this->unknown7 = ($message->unknown7 !== null) ? $message->unknown7 : $this->unknown7;
        $this->payload = ($message->payload !== null) ? $message->payload : $this->payload;
    }


}

