<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo\ResponseEnvelop;

/**
 * Protobuf message : pokemongo.ResponseEnvelop.NearbyPokemonProto
 */
class NearbyPokemonProto extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * PokedexNumber optional int32 = 1
     *
     * @var int
     */
    protected $PokedexNumber = null;

    /**
     * DistanceMeters optional float = 2
     *
     * @var float
     */
    protected $DistanceMeters = null;

    /**
     * EncounterId optional uint64 = 3
     *
     * @var int
     */
    protected $EncounterId = null;

    /**
     * Check if 'PokedexNumber' has a value
     *
     * @return bool
     */
    public function hasPokedexNumber()
    {
        return $this->PokedexNumber !== null;
    }

    /**
     * Get 'PokedexNumber' value
     *
     * @return int
     */
    public function getPokedexNumber()
    {
        return $this->PokedexNumber;
    }

    /**
     * Set 'PokedexNumber' value
     *
     * @param int $value
     */
    public function setPokedexNumber($value = null)
    {
        $this->PokedexNumber = $value;
    }

    /**
     * Check if 'DistanceMeters' has a value
     *
     * @return bool
     */
    public function hasDistanceMeters()
    {
        return $this->DistanceMeters !== null;
    }

    /**
     * Get 'DistanceMeters' value
     *
     * @return float
     */
    public function getDistanceMeters()
    {
        return $this->DistanceMeters;
    }

    /**
     * Set 'DistanceMeters' value
     *
     * @param float $value
     */
    public function setDistanceMeters($value = null)
    {
        $this->DistanceMeters = $value;
    }

    /**
     * Check if 'EncounterId' has a value
     *
     * @return bool
     */
    public function hasEncounterId()
    {
        return $this->EncounterId !== null;
    }

    /**
     * Get 'EncounterId' value
     *
     * @return int
     */
    public function getEncounterId()
    {
        return $this->EncounterId;
    }

    /**
     * Set 'EncounterId' value
     *
     * @param int $value
     */
    public function setEncounterId($value = null)
    {
        $this->EncounterId = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'PokedexNumber' => null,
            'DistanceMeters' => null,
            'EncounterId' => null
        ], $values);

        $message->setPokedexNumber($values['PokedexNumber']);
        $message->setDistanceMeters($values['DistanceMeters']);
        $message->setEncounterId($values['EncounterId']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'NearbyPokemonProto',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'PokedexNumber',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'DistanceMeters',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FLOAT(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'EncounterId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->PokedexNumber !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->PokedexNumber);
        }

        if ($this->DistanceMeters !== null) {
            $writer->writeVarint($stream, 21);
            $writer->writeFloat($stream, $this->DistanceMeters);
        }

        if ($this->EncounterId !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->EncounterId);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->PokedexNumber = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 2);

                $this->DistanceMeters = $reader->readFloat($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->EncounterId = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->PokedexNumber !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->PokedexNumber);
        }

        if ($this->DistanceMeters !== null) {
            $size += 1;
            $size += 4;
        }

        if ($this->EncounterId !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->EncounterId);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->PokedexNumber = null;
        $this->DistanceMeters = null;
        $this->EncounterId = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->PokedexNumber = ($message->PokedexNumber !== null) ? $message->PokedexNumber : $this->PokedexNumber;
        $this->DistanceMeters = ($message->DistanceMeters !== null) ? $message->DistanceMeters : $this->DistanceMeters;
        $this->EncounterId = ($message->EncounterId !== null) ? $message->EncounterId : $this->EncounterId;
    }


}

