<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo\ResponseEnvelop;

/**
 * Protobuf message : pokemongo.ResponseEnvelop.WildPokemon
 */
class WildPokemon extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * UniqueId required string = 1
     *
     * @var string
     */
    protected $UniqueId = null;

    /**
     * PokemonId required string = 2
     *
     * @var string
     */
    protected $PokemonId = null;

    /**
     * pokemon repeated message = 11
     *
     * @var \Protobuf\Collection<\Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto>
     */
    protected $pokemon = null;

    /**
     * Check if 'UniqueId' has a value
     *
     * @return bool
     */
    public function hasUniqueId()
    {
        return $this->UniqueId !== null;
    }

    /**
     * Get 'UniqueId' value
     *
     * @return string
     */
    public function getUniqueId()
    {
        return $this->UniqueId;
    }

    /**
     * Set 'UniqueId' value
     *
     * @param string $value
     */
    public function setUniqueId($value)
    {
        $this->UniqueId = $value;
    }

    /**
     * Check if 'PokemonId' has a value
     *
     * @return bool
     */
    public function hasPokemonId()
    {
        return $this->PokemonId !== null;
    }

    /**
     * Get 'PokemonId' value
     *
     * @return string
     */
    public function getPokemonId()
    {
        return $this->PokemonId;
    }

    /**
     * Set 'PokemonId' value
     *
     * @param string $value
     */
    public function setPokemonId($value)
    {
        $this->PokemonId = $value;
    }

    /**
     * Check if 'pokemon' has a value
     *
     * @return bool
     */
    public function hasPokemonList()
    {
        return $this->pokemon !== null;
    }

    /**
     * Get 'pokemon' value
     *
     * @return \Protobuf\Collection<\Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto>
     */
    public function getPokemonList()
    {
        return $this->pokemon;
    }

    /**
     * Set 'pokemon' value
     *
     * @param \Protobuf\Collection<\Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto> $value
     */
    public function setPokemonList(\Protobuf\Collection $value = null)
    {
        $this->pokemon = $value;
    }

    /**
     * Add a new element to 'pokemon'
     *
     * @param \Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto $value
     */
    public function addPokemon(\Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto $value)
    {
        if ($this->pokemon === null) {
            $this->pokemon = new \Protobuf\MessageCollection();
        }

        $this->pokemon->add($value);
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['UniqueId'])) {
            throw new \InvalidArgumentException('Field "UniqueId" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['PokemonId'])) {
            throw new \InvalidArgumentException('Field "PokemonId" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'pokemon' => []
        ], $values);

        $message->setUniqueId($values['UniqueId']);
        $message->setPokemonId($values['PokemonId']);

        foreach ($values['pokemon'] as $item) {
            $message->addPokemon($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'WildPokemon',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'UniqueId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'PokemonId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 11,
                    'name' => 'pokemon',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.pokemongo.ResponseEnvelop.NearbyPokemonProto'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->UniqueId === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\ResponseEnvelop\\WildPokemon#UniqueId" (tag 1) is required but has no value.');
        }

        if ($this->PokemonId === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\ResponseEnvelop\\WildPokemon#PokemonId" (tag 2) is required but has no value.');
        }

        if ($this->UniqueId !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->UniqueId);
        }

        if ($this->PokemonId !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->PokemonId);
        }

        if ($this->pokemon !== null) {
            foreach ($this->pokemon as $val) {
                $writer->writeVarint($stream, 90);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->UniqueId = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->PokemonId = $reader->readString($stream);

                continue;
            }

            if ($tag === 11) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\ResponseEnvelop\NearbyPokemonProto();

                if ($this->pokemon === null) {
                    $this->pokemon = new \Protobuf\MessageCollection();
                }

                $this->pokemon->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->UniqueId !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->UniqueId);
        }

        if ($this->PokemonId !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->PokemonId);
        }

        if ($this->pokemon !== null) {
            foreach ($this->pokemon as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->UniqueId = null;
        $this->PokemonId = null;
        $this->pokemon = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\ResponseEnvelop\WildPokemon) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->UniqueId = ($message->UniqueId !== null) ? $message->UniqueId : $this->UniqueId;
        $this->PokemonId = ($message->PokemonId !== null) ? $message->PokemonId : $this->PokemonId;
        $this->pokemon = ($message->pokemon !== null) ? $message->pokemon : $this->pokemon;
    }


}

