<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo\ResponseEnvelop;

/**
 * Protobuf message : pokemongo.ResponseEnvelop.WildPokemonProto
 */
class WildPokemonProto extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * EncounterId optional uint64 = 1
     *
     * @var int
     */
    protected $EncounterId = null;

    /**
     * LastModifiedMs optional int64 = 2
     *
     * @var int
     */
    protected $LastModifiedMs = null;

    /**
     * Latitude optional double = 3
     *
     * @var float
     */
    protected $Latitude = null;

    /**
     * Longitude optional double = 4
     *
     * @var float
     */
    protected $Longitude = null;

    /**
     * SpawnPointId optional string = 5
     *
     * @var string
     */
    protected $SpawnPointId = null;

    /**
     * pokemon optional message = 7
     *
     * @var \Protobuf\PokemonGo\ResponseEnvelop\WildPokemonProto\Pokemon
     */
    protected $pokemon = null;

    /**
     * TimeTillHiddenMs optional int32 = 11
     *
     * @var int
     */
    protected $TimeTillHiddenMs = null;

    /**
     * Check if 'EncounterId' has a value
     *
     * @return bool
     */
    public function hasEncounterId()
    {
        return $this->EncounterId !== null;
    }

    /**
     * Get 'EncounterId' value
     *
     * @return int
     */
    public function getEncounterId()
    {
        return $this->EncounterId;
    }

    /**
     * Set 'EncounterId' value
     *
     * @param int $value
     */
    public function setEncounterId($value = null)
    {
        $this->EncounterId = $value;
    }

    /**
     * Check if 'LastModifiedMs' has a value
     *
     * @return bool
     */
    public function hasLastModifiedMs()
    {
        return $this->LastModifiedMs !== null;
    }

    /**
     * Get 'LastModifiedMs' value
     *
     * @return int
     */
    public function getLastModifiedMs()
    {
        return $this->LastModifiedMs;
    }

    /**
     * Set 'LastModifiedMs' value
     *
     * @param int $value
     */
    public function setLastModifiedMs($value = null)
    {
        $this->LastModifiedMs = $value;
    }

    /**
     * Check if 'Latitude' has a value
     *
     * @return bool
     */
    public function hasLatitude()
    {
        return $this->Latitude !== null;
    }

    /**
     * Get 'Latitude' value
     *
     * @return float
     */
    public function getLatitude()
    {
        return $this->Latitude;
    }

    /**
     * Set 'Latitude' value
     *
     * @param float $value
     */
    public function setLatitude($value = null)
    {
        $this->Latitude = $value;
    }

    /**
     * Check if 'Longitude' has a value
     *
     * @return bool
     */
    public function hasLongitude()
    {
        return $this->Longitude !== null;
    }

    /**
     * Get 'Longitude' value
     *
     * @return float
     */
    public function getLongitude()
    {
        return $this->Longitude;
    }

    /**
     * Set 'Longitude' value
     *
     * @param float $value
     */
    public function setLongitude($value = null)
    {
        $this->Longitude = $value;
    }

    /**
     * Check if 'SpawnPointId' has a value
     *
     * @return bool
     */
    public function hasSpawnPointId()
    {
        return $this->SpawnPointId !== null;
    }

    /**
     * Get 'SpawnPointId' value
     *
     * @return string
     */
    public function getSpawnPointId()
    {
        return $this->SpawnPointId;
    }

    /**
     * Set 'SpawnPointId' value
     *
     * @param string $value
     */
    public function setSpawnPointId($value = null)
    {
        $this->SpawnPointId = $value;
    }

    /**
     * Check if 'pokemon' has a value
     *
     * @return bool
     */
    public function hasPokemon()
    {
        return $this->pokemon !== null;
    }

    /**
     * Get 'pokemon' value
     *
     * @return \Protobuf\PokemonGo\ResponseEnvelop\WildPokemonProto\Pokemon
     */
    public function getPokemon()
    {
        return $this->pokemon;
    }

    /**
     * Set 'pokemon' value
     *
     * @param \Protobuf\PokemonGo\ResponseEnvelop\WildPokemonProto\Pokemon $value
     */
    public function setPokemon(\Protobuf\PokemonGo\ResponseEnvelop\WildPokemonProto\Pokemon $value = null)
    {
        $this->pokemon = $value;
    }

    /**
     * Check if 'TimeTillHiddenMs' has a value
     *
     * @return bool
     */
    public function hasTimeTillHiddenMs()
    {
        return $this->TimeTillHiddenMs !== null;
    }

    /**
     * Get 'TimeTillHiddenMs' value
     *
     * @return int
     */
    public function getTimeTillHiddenMs()
    {
        return $this->TimeTillHiddenMs;
    }

    /**
     * Set 'TimeTillHiddenMs' value
     *
     * @param int $value
     */
    public function setTimeTillHiddenMs($value = null)
    {
        $this->TimeTillHiddenMs = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'EncounterId' => null,
            'LastModifiedMs' => null,
            'Latitude' => null,
            'Longitude' => null,
            'SpawnPointId' => null,
            'pokemon' => null,
            'TimeTillHiddenMs' => null
        ], $values);

        $message->setEncounterId($values['EncounterId']);
        $message->setLastModifiedMs($values['LastModifiedMs']);
        $message->setLatitude($values['Latitude']);
        $message->setLongitude($values['Longitude']);
        $message->setSpawnPointId($values['SpawnPointId']);
        $message->setPokemon($values['pokemon']);
        $message->setTimeTillHiddenMs($values['TimeTillHiddenMs']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'WildPokemonProto',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'EncounterId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'LastModifiedMs',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'Latitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'Longitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'SpawnPointId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 7,
                    'name' => 'pokemon',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pokemongo.ResponseEnvelop.WildPokemonProto.Pokemon'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 11,
                    'name' => 'TimeTillHiddenMs',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->EncounterId !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->EncounterId);
        }

        if ($this->LastModifiedMs !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->LastModifiedMs);
        }

        if ($this->Latitude !== null) {
            $writer->writeVarint($stream, 25);
            $writer->writeDouble($stream, $this->Latitude);
        }

        if ($this->Longitude !== null) {
            $writer->writeVarint($stream, 33);
            $writer->writeDouble($stream, $this->Longitude);
        }

        if ($this->SpawnPointId !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeString($stream, $this->SpawnPointId);
        }

        if ($this->pokemon !== null) {
            $writer->writeVarint($stream, 58);
            $writer->writeVarint($stream, $this->pokemon->serializedSize($sizeContext));
            $this->pokemon->writeTo($context);
        }

        if ($this->TimeTillHiddenMs !== null) {
            $writer->writeVarint($stream, 88);
            $writer->writeVarint($stream, $this->TimeTillHiddenMs);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->EncounterId = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 3);

                $this->LastModifiedMs = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->Latitude = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->Longitude = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->SpawnPointId = $reader->readString($stream);

                continue;
            }

            if ($tag === 7) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Protobuf\PokemonGo\ResponseEnvelop\WildPokemonProto\Pokemon();

                $this->pokemon = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 11) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->TimeTillHiddenMs = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->EncounterId !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->EncounterId);
        }

        if ($this->LastModifiedMs !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->LastModifiedMs);
        }

        if ($this->Latitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->Longitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->SpawnPointId !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->SpawnPointId);
        }

        if ($this->pokemon !== null) {
            $innerSize = $this->pokemon->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->TimeTillHiddenMs !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->TimeTillHiddenMs);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->EncounterId = null;
        $this->LastModifiedMs = null;
        $this->Latitude = null;
        $this->Longitude = null;
        $this->SpawnPointId = null;
        $this->pokemon = null;
        $this->TimeTillHiddenMs = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\ResponseEnvelop\WildPokemonProto) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->EncounterId = ($message->EncounterId !== null) ? $message->EncounterId : $this->EncounterId;
        $this->LastModifiedMs = ($message->LastModifiedMs !== null) ? $message->LastModifiedMs : $this->LastModifiedMs;
        $this->Latitude = ($message->Latitude !== null) ? $message->Latitude : $this->Latitude;
        $this->Longitude = ($message->Longitude !== null) ? $message->Longitude : $this->Longitude;
        $this->SpawnPointId = ($message->SpawnPointId !== null) ? $message->SpawnPointId : $this->SpawnPointId;
        $this->pokemon = ($message->pokemon !== null) ? $message->pokemon : $this->pokemon;
        $this->TimeTillHiddenMs = ($message->TimeTillHiddenMs !== null) ? $message->TimeTillHiddenMs : $this->TimeTillHiddenMs;
    }


}

