<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo\RequestEnvelop;

/**
 * Protobuf message : pokemongo.RequestEnvelop.MessageTwoInts
 */
class MessageTwoInts extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * f1 required int64 = 1
     *
     * @var int
     */
    protected $f1 = null;

    /**
     * f5 required int64 = 5
     *
     * @var int
     */
    protected $f5 = null;

    /**
     * Check if 'f1' has a value
     *
     * @return bool
     */
    public function hasF1()
    {
        return $this->f1 !== null;
    }

    /**
     * Get 'f1' value
     *
     * @return int
     */
    public function getF1()
    {
        return $this->f1;
    }

    /**
     * Set 'f1' value
     *
     * @param int $value
     */
    public function setF1($value)
    {
        $this->f1 = $value;
    }

    /**
     * Check if 'f5' has a value
     *
     * @return bool
     */
    public function hasF5()
    {
        return $this->f5 !== null;
    }

    /**
     * Get 'f5' value
     *
     * @return int
     */
    public function getF5()
    {
        return $this->f5;
    }

    /**
     * Set 'f5' value
     *
     * @param int $value
     */
    public function setF5($value)
    {
        $this->f5 = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['f1'])) {
            throw new \InvalidArgumentException('Field "f1" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['f5'])) {
            throw new \InvalidArgumentException('Field "f5" (tag 5) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
        ], $values);

        $message->setF1($values['f1']);
        $message->setF5($values['f5']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'MessageTwoInts',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'f1',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'f5',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->f1 === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop\\MessageTwoInts#f1" (tag 1) is required but has no value.');
        }

        if ($this->f5 === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop\\MessageTwoInts#f5" (tag 5) is required but has no value.');
        }

        if ($this->f1 !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->f1);
        }

        if ($this->f5 !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->f5);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 3);

                $this->f1 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 3);

                $this->f5 = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->f1 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->f1);
        }

        if ($this->f5 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->f5);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->f1 = null;
        $this->f5 = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\RequestEnvelop\MessageTwoInts) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->f1 = ($message->f1 !== null) ? $message->f1 : $this->f1;
        $this->f5 = ($message->f5 !== null) ? $message->f5 : $this->f5;
    }


}

