<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo\RequestEnvelop;

/**
 * Protobuf message : pokemongo.RequestEnvelop.MessageQuad
 */
class MessageQuad extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * f1 required bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $f1 = null;

    /**
     * f2 required bytes = 2
     *
     * @var \Protobuf\Stream
     */
    protected $f2 = null;

    /**
     * lat required fixed64 = 3
     *
     * @var int
     */
    protected $lat = null;

    /**
     * long required fixed64 = 4
     *
     * @var int
     */
    protected $long = null;

    /**
     * Check if 'f1' has a value
     *
     * @return bool
     */
    public function hasF1()
    {
        return $this->f1 !== null;
    }

    /**
     * Get 'f1' value
     *
     * @return \Protobuf\Stream
     */
    public function getF1()
    {
        return $this->f1;
    }

    /**
     * Set 'f1' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setF1($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->f1 = $value;
    }

    /**
     * Check if 'f2' has a value
     *
     * @return bool
     */
    public function hasF2()
    {
        return $this->f2 !== null;
    }

    /**
     * Get 'f2' value
     *
     * @return \Protobuf\Stream
     */
    public function getF2()
    {
        return $this->f2;
    }

    /**
     * Set 'f2' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setF2($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->f2 = $value;
    }

    /**
     * Check if 'lat' has a value
     *
     * @return bool
     */
    public function hasLat()
    {
        return $this->lat !== null;
    }

    /**
     * Get 'lat' value
     *
     * @return int
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Set 'lat' value
     *
     * @param int $value
     */
    public function setLat($value)
    {
        $this->lat = $value;
    }

    /**
     * Check if 'long' has a value
     *
     * @return bool
     */
    public function hasLong()
    {
        return $this->long !== null;
    }

    /**
     * Get 'long' value
     *
     * @return int
     */
    public function getLong()
    {
        return $this->long;
    }

    /**
     * Set 'long' value
     *
     * @param int $value
     */
    public function setLong($value)
    {
        $this->long = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['f1'])) {
            throw new \InvalidArgumentException('Field "f1" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['f2'])) {
            throw new \InvalidArgumentException('Field "f2" (tag 2) is required but has no value.');
        }

        if ( ! isset($values['lat'])) {
            throw new \InvalidArgumentException('Field "lat" (tag 3) is required but has no value.');
        }

        if ( ! isset($values['long'])) {
            throw new \InvalidArgumentException('Field "long" (tag 4) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
        ], $values);

        $message->setF1($values['f1']);
        $message->setF2($values['f2']);
        $message->setLat($values['lat']);
        $message->setLong($values['long']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'MessageQuad',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'f1',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'f2',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'lat',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'long',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->f1 === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop\\MessageQuad#f1" (tag 1) is required but has no value.');
        }

        if ($this->f2 === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop\\MessageQuad#f2" (tag 2) is required but has no value.');
        }

        if ($this->lat === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop\\MessageQuad#lat" (tag 3) is required but has no value.');
        }

        if ($this->long === null) {
            throw new \UnexpectedValueException('Field "\\Protobuf\\PokemonGo\\RequestEnvelop\\MessageQuad#long" (tag 4) is required but has no value.');
        }

        if ($this->f1 !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeByteStream($stream, $this->f1);
        }

        if ($this->f2 !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeByteStream($stream, $this->f2);
        }

        if ($this->lat !== null) {
            $writer->writeVarint($stream, 25);
            $writer->writeFixed64($stream, $this->lat);
        }

        if ($this->long !== null) {
            $writer->writeVarint($stream, 33);
            $writer->writeFixed64($stream, $this->long);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->f1 = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->f2 = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->lat = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->long = $reader->readFixed64($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->f1 !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->f1);
        }

        if ($this->f2 !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->f2);
        }

        if ($this->lat !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->long !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->f1 = null;
        $this->f2 = null;
        $this->lat = null;
        $this->long = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\RequestEnvelop\MessageQuad) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->f1 = ($message->f1 !== null) ? $message->f1 : $this->f1;
        $this->f2 = ($message->f2 !== null) ? $message->f2 : $this->f2;
        $this->lat = ($message->lat !== null) ? $message->lat : $this->lat;
        $this->long = ($message->long !== null) ? $message->long : $this->long;
    }


}

