<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : pokemongo.proto
 */


namespace Protobuf\PokemonGo\ResponseEnvelop\Profile;

/**
 * Protobuf message : pokemongo.ResponseEnvelop.Profile.AvatarDetails
 */
class AvatarDetails extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * unknown2 optional int32 = 2
     *
     * @var int
     */
    protected $unknown2 = null;

    /**
     * unknown3 optional int32 = 3
     *
     * @var int
     */
    protected $unknown3 = null;

    /**
     * unknown9 optional int32 = 9
     *
     * @var int
     */
    protected $unknown9 = null;

    /**
     * unknown10 optional int32 = 10
     *
     * @var int
     */
    protected $unknown10 = null;

    /**
     * Check if 'unknown2' has a value
     *
     * @return bool
     */
    public function hasUnknown2()
    {
        return $this->unknown2 !== null;
    }

    /**
     * Get 'unknown2' value
     *
     * @return int
     */
    public function getUnknown2()
    {
        return $this->unknown2;
    }

    /**
     * Set 'unknown2' value
     *
     * @param int $value
     */
    public function setUnknown2($value = null)
    {
        $this->unknown2 = $value;
    }

    /**
     * Check if 'unknown3' has a value
     *
     * @return bool
     */
    public function hasUnknown3()
    {
        return $this->unknown3 !== null;
    }

    /**
     * Get 'unknown3' value
     *
     * @return int
     */
    public function getUnknown3()
    {
        return $this->unknown3;
    }

    /**
     * Set 'unknown3' value
     *
     * @param int $value
     */
    public function setUnknown3($value = null)
    {
        $this->unknown3 = $value;
    }

    /**
     * Check if 'unknown9' has a value
     *
     * @return bool
     */
    public function hasUnknown9()
    {
        return $this->unknown9 !== null;
    }

    /**
     * Get 'unknown9' value
     *
     * @return int
     */
    public function getUnknown9()
    {
        return $this->unknown9;
    }

    /**
     * Set 'unknown9' value
     *
     * @param int $value
     */
    public function setUnknown9($value = null)
    {
        $this->unknown9 = $value;
    }

    /**
     * Check if 'unknown10' has a value
     *
     * @return bool
     */
    public function hasUnknown10()
    {
        return $this->unknown10 !== null;
    }

    /**
     * Get 'unknown10' value
     *
     * @return int
     */
    public function getUnknown10()
    {
        return $this->unknown10;
    }

    /**
     * Set 'unknown10' value
     *
     * @param int $value
     */
    public function setUnknown10($value = null)
    {
        $this->unknown10 = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'unknown2' => null,
            'unknown3' => null,
            'unknown9' => null,
            'unknown10' => null
        ], $values);

        $message->setUnknown2($values['unknown2']);
        $message->setUnknown3($values['unknown3']);
        $message->setUnknown9($values['unknown9']);
        $message->setUnknown10($values['unknown10']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'AvatarDetails',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'unknown2',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'unknown3',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 9,
                    'name' => 'unknown9',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 10,
                    'name' => 'unknown10',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->unknown2 !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->unknown2);
        }

        if ($this->unknown3 !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->unknown3);
        }

        if ($this->unknown9 !== null) {
            $writer->writeVarint($stream, 72);
            $writer->writeVarint($stream, $this->unknown9);
        }

        if ($this->unknown10 !== null) {
            $writer->writeVarint($stream, 80);
            $writer->writeVarint($stream, $this->unknown10);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->unknown2 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->unknown3 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 9) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->unknown9 = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 10) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->unknown10 = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->unknown2 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown2);
        }

        if ($this->unknown3 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown3);
        }

        if ($this->unknown9 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown9);
        }

        if ($this->unknown10 !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->unknown10);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->unknown2 = null;
        $this->unknown3 = null;
        $this->unknown9 = null;
        $this->unknown10 = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Protobuf\PokemonGo\ResponseEnvelop\Profile\AvatarDetails) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->unknown2 = ($message->unknown2 !== null) ? $message->unknown2 : $this->unknown2;
        $this->unknown3 = ($message->unknown3 !== null) ? $message->unknown3 : $this->unknown3;
        $this->unknown9 = ($message->unknown9 !== null) ? $message->unknown9 : $this->unknown9;
        $this->unknown10 = ($message->unknown10 !== null) ? $message->unknown10 : $this->unknown10;
    }


}

